# Generated by Django 5.1.7 on 2025-03-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.CharField(default='', max_length=255, verbose_name='职位类型')),
                ('city', models.CharField(default='', max_length=255, verbose_name='城市')),
                ('title', models.CharField(default='', max_length=255, verbose_name='职位名称')),
                ('company', models.CharField(default='', max_length=255, verbose_name='公司名称')),
                ('minsalary', models.IntegerField(default=0, verbose_name='最低薪资')),
                ('maxsalary', models.IntegerField(default=0, verbose_name='最高薪资')),
                ('work_experience', models.CharField(default='', max_length=255, verbose_name='工作经验')),
                ('education', models.CharField(default='', max_length=255, verbose_name='学历要求')),
                ('com_tag', models.TextField(default='', verbose_name='公司标签')),
                ('com_People', models.CharField(default='', max_length=255, verbose_name='公司规模')),
                ('workTag', models.TextField(default='', verbose_name='工作标签')),
                ('welfare', models.TextField(default='', verbose_name='员工福利')),
                ('imgSrc', models.TextField(default='', verbose_name='公司Logo')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '职位数据',
                'verbose_name_plural': '职位数据',
                'db_table': 'jobData',
            },
        ),
    ]
