# Generated by Django 5.1.7 on 2025-03-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_jobdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='职位')),
                ('address', models.CharField(max_length=255, verbose_name='工作地址')),
                ('post_time', models.DateTimeField(verbose_name='发布时间')),
                ('work_experience', models.CharField(max_length=255, verbose_name='工作经验')),
                ('education', models.CharField(max_length=255, verbose_name='学历')),
                ('salary', models.CharField(max_length=255, verbose_name='薪资范围')),
                ('company', models.CharField(max_length=255, verbose_name='公司')),
                ('workTag', models.TextField(verbose_name='工作标签')),
                ('welfare', models.TextField(verbose_name='工作福利')),
                ('work_content', models.TextField(verbose_name='职位描述')),
            ],
            options={
                'db_table': 'recomdata',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='jobdata',
            options={'managed': False},
        ),
    ]
