# Generated by Django 5.1.7 on 2025-03-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_recomdata_alter_jobdata_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobdata',
            table='jobdata',
        ),
    ]
