# Generated by Django 5.1.7 on 2025-03-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_jobdata_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recomdata',
            options={'managed': True},
        ),
    ]
