# Generated by Django 5.1.7 on 2025-03-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_recomdata_options_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='cityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('beijing', '北京'), ('shanghai', '上海'), ('guangzhou', '广州'), ('shenzhen', '深圳'), ('hangzhou', '杭州'), ('chengdu', '成都')], max_length=20, verbose_name='城市')),
                ('programming_language', models.CharField(choices=[('java', 'Java'), ('cpp', 'C++'), ('python', 'Python'), ('php', 'PHP')], max_length=20, verbose_name='编程语言')),
                ('job_count', models.IntegerField(default=0, verbose_name='招聘数量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'cityData',
                'unique_together': {('city', 'programming_language')},
            },
        ),
    ]
